name: Behat Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'composer.*'
      - 'behat.*'
      - 'src/**'
      - 'resources/**'
      - 'tests/Behat/**'
      - 'tests/fixtures/**'
  push:
    paths:
      - 'composer.*'
      - 'behat.*'
      - 'src/**'
      - 'resources/**'
      - 'tests/Behat/**'
      - 'tests/fixtures/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    strategy:
      matrix:
        php-version: [ '7.2', '7.3', '7.4' ]
        composer-version: [ 'v1', 'v2' ]
        include:
          - php-version: '8.0'
            composer-version: 'v2'
          - php-version: '8.1'
            composer-version: 'v2'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:${{ matrix.composer-version }}
          coverage: none
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On

      - name: Use Behat as regular dependency so we can run Composer with --no-dev
        run: |
          composer remove behat/behat ondram/ci-detector --dev --no-update
          composer require behat/behat:^3.10 ondram/ci-detector:^4.1 --no-update

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist --no-dev"

      - name: Run Behat
        run: ./vendor/bin/behat --colors
