name: Code Style

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/code-style.yml'
      - 'composer.*'
      - 'phpcs*'
      - '**.php'
  push:
    paths:
      - '**/code-style.yml'
      - 'composer.*'
      - 'phpcs*'
      - '**.php'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-code-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main