name: Integration Tests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        php-versions: [ '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit
        run: composer tests:integration