name: Static Analysis

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'composer.*'
      - '**.php'
      - 'psalm*'
      - 'phpcs*'
  push:
    paths:
      - 'composer.*'
      - '**.php'
      - 'psalm*'
      - 'phpcs*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-code-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
    with:
      PSALM_ARGS: '--output-format=github --no-cache --find-unused-psalm-suppress'
