name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.php'
      - 'phpunit*'
  push:
    paths:
      - '**.php'
      - 'phpunit*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-unit-php:
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    secrets:
      COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}
    with:
      PHPUNIT_ARGS: '--testsuite=Unit --coverage-text'
      PHP_MATRIX: >-
        ["7.2", "7.3", "7.4", "8.0", "8.1"]
